call plug#begin('~/.vim/plugged')
" text object fundations
Plug 'kana/vim-textobj-user'
" entire buffer text object
Plug 'kana/vim-textobj-entire'
" line text object
Plug 'kana/vim-textobj-line'
" surroundings of text actions (parenthesis, quotes, brackets, etc.)
Plug 'tpope/vim-surround'
" comment action
Plug 'tpope/vim-commentary'
call plug#end()
syntax on
filetype plugin indent on
set relativenumber
set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab
set foldmethod=indent
set foldlevel=5
set colorcolumn=81
set wildmenu
set pastetoggle=<F3>
let mapleader=','
nmap <leader>nt :tabnext<CR>
nmap <leader>pt :tabprevious<CR>
